(function(){'use strict';var g=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},k=function(a){if(g(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&g(a))return a;return null};var l=/[^\d]+$/,n=function(a,c,d,b){if(!a.hasAttribute(c))return d;a=a.getAttribute(c);isNaN(parseFloat(a))?b=d:(d=parseFloat(a),(a=(a=a.match(l))&&a[0]||null)&&(a=a.trim()),c=d,"%"==a&&(c=Number((d/100*b).toFixed(2))),b=c);return b};var p=function(a,c,d,b){if(0>=b)return a;if(1<=b)return c;switch(d){case "ease-in":d=b*b*b;break;case "ease-in-out":d=3*b*b-2*b*b*b;break;case "ease-out":d=1-b;d=1-d*d*d;break;default:d=b}return(c-a)*d+a},q=function(a,c){if(!a.hasAttribute(c))return 1;a=a.getAttribute(c);a=parseFloat(a);return isNaN(a)?1:0>a?0:1<a?1:a};var r=function(){};goog.inherits(r,HTMLElement);r.prototype.createdCallback=function(){this.f=[];this.c=this.o=null;this.a=[];this.h=this.v.bind(this);this.s=this.l=!1;this.g=this.w.bind(this);this.b=null};
r.prototype.attachedCallback=function(){Enabler.isServingInLiveEnvironment()?Enabler.addEventListener(studio.events.StudioEvent.HOSTPAGE_SCROLL,this.g,!1):window.addEventListener("message",this.g,!1);if("function"==typeof this.gwdLoad&&"function"==typeof this.gwdIsLoaded&&!this.gwdIsLoaded()){var a=k(this),c=a&&"function"==typeof a.gwdIsLoaded;(!a||c&&a.gwdIsLoaded())&&this.gwdLoad()}};
r.prototype.detachedCallback=function(){Enabler.isServingInLiveEnvironment()?Enabler.removeEventListener(studio.events.StudioEvent.HOSTPAGE_SCROLL,this.g,!1):window.removeEventListener("message",this.g,!1);this.removeEventListener("ready",this.h,!1)};
r.prototype.gwdLoad=function(){if(!this.gwdIsLoaded()){this.a.length=0;t(this);for(var a=this.a.length-1;0<=a;a--)this.a[a].gwdLoad();this.a=this.a.filter(function(c){return!c.gwdIsLoaded()});0==this.a.length?u(this):this.addEventListener("ready",this.h,!1)}};r.prototype.gwdIsLoaded=function(){return this.l&&0==this.a.length};r.prototype.v=function(a){a=this.a.indexOf(a.target);0<=a&&(this.a.splice(a,1),0==this.a.length&&(u(this),this.removeEventListener("ready",this.h,!1)))};
var u=function(a){if(!a.s){var c=document.createEvent("Event");c.initEvent("ready",!0,!0);a.dispatchEvent(c)}a.s=!0;a.b&&(v(a,a.b.creativeFramePercentY,a.b.windowHeight+a.c),a.b=null)},t=function(a){a.style.overflow="hidden";a.f.length=0;a.o=a.clientWidth;a.c=a.clientHeight;for(var c=a.ownerDocument,d=0;d<a.children.length;d++){var b=a.children[d],e=a.o,h=a.c,f=n(b,"xenter",0,e),m=n(b,"xexit",0,e),w=n(b,"yenter",0,h),x=n(b,"yexit",0,h),y=q(b,"opacityenter"),z=q(b,"opacityexit"),A=b.hasAttribute("fixed"),
B=b.getAttribute("assettype")||"",C=b.getAttribute("source")||"",D=b.getAttribute("easing")||"linear";e=n(b,"width",e,e);h=n(b,"height",h,h);b={u:B,easing:D,element:b,fixed:A,height:h,m:y,A:z,source:C,width:e,i:f,j:w,B:m,C:x};a.f.push(b);b.element.style.position="absolute";b.element.style.left="0px";b.element.style.top="0px";b.element.style.width=b.width+"px";b.element.style.height=b.height+"px";b.element.style.transform="translate("+b.i+"px, "+b.j+"px)";b.element.style.opacity=b.m+"";if("image"==
b.u&&b.source){for(;b.element.firstChild;)b.element.removeChild(b.element.firstChild);f=c.createElement("gwd-image");f.style.width="100%";f.style.height="100%";f.setAttribute("source",b.source);a.a.push(f);b.element.appendChild(f)}}a.l=!0};
r.prototype.w=function(a){if(Enabler.isServingInLiveEnvironment())var c=a;else{if(!a.data||"string"!==typeof a.data)return;try{c=JSON.parse(a.data)}catch(d){return}if(c.eventType!=studio.events.StudioEvent.HOSTPAGE_SCROLL)return}a=c;this.gwdIsLoaded()?v(this,a.creativeFramePercentY,a.windowHeight+this.c):this.b=a};
var v=function(a,c,d){for(var b=0;b<a.f.length;b++){var e=a.f[b];if(e.fixed){var h=e.i;var f=e.j+c*d}else h=p(e.i,e.B,e.easing,c),f=p(e.j,e.C,e.easing,c);var m=p(e.m,e.A,e.easing,c);e.element.style.transform="translate("+h+"px, "+f+"px)";e.element.style.opacity=m+""}};document.registerElement("gwd-parallax",{prototype:r.prototype});}).call(this);
