(function(){'use strict';var c;var f=/^https:\/\/www\.gstatic\.com\/vr\/ads\/index\.html\?assetId=(staging\/)?([\w-_]+)$/,g=/^https:\/\/poly\.google\.com\/view\/([\w-_]+)$/;var h={TimeToFirstFrame:function(){Enabler.startTimer("TimeToFirstFrame")},TimeToSpritesheet:function(){Enabler.startTimer("TimeToSpritesheet")},TotalEngagement:function(){Enabler.startTimer("TotalEngagement")}},k={TimeToFirstFrame:function(){Enabler.stopTimer("TimeToFirstFrame")},TimeToSpritesheet:function(){Enabler.stopTimer("TimeToSpritesheet")},TotalEngagement:function(){Enabler.stopTimer("TotalEngagement")}},l={Engagement:function(){Enabler.reportEngagement()},Zoom:function(){Enabler.counter("Zoom",
!0)},Pan:function(){Enabler.counter("Pan",!0)},Rotate:function(){Enabler.counter("Rotate",!0)},SpritesheetRotate:function(){Enabler.counter("SpritesheetRotate",!0)}},m={"SpritesheetEngagementDuration0-450":function(){Enabler.counter("SpritesheetEngagementDuration0-450")},"TotalEngagementDuration0-450":function(){Enabler.counter("TotalEngagementDuration0-450")},"TotalSessionDuration0-450":function(){Enabler.counter("TotalSessionDuration0-450")},"SpritesheetEngagementDuration450-675":function(){Enabler.counter("SpritesheetEngagementDuration450-675")},
"TotalEngagementDuration450-675":function(){Enabler.counter("TotalEngagementDuration450-675")},"TotalSessionDuration450-675":function(){Enabler.counter("TotalSessionDuration450-675")},"SpritesheetEngagementDuration675-1012":function(){Enabler.counter("SpritesheetEngagementDuration675-1012")},"TotalEngagementDuration675-1012":function(){Enabler.counter("TotalEngagementDuration675-1012")},"TotalSessionDuration675-1012":function(){Enabler.counter("TotalSessionDuration675-1012")},"SpritesheetEngagementDuration1012-1518":function(){Enabler.counter("SpritesheetEngagementDuration1012-1518")},
"TotalEngagementDuration1012-1518":function(){Enabler.counter("TotalEngagementDuration1012-1518")},"TotalSessionDuration1012-1518":function(){Enabler.counter("TotalSessionDuration1012-1518")},"SpritesheetEngagementDuration1518-2278":function(){Enabler.counter("SpritesheetEngagementDuration1518-2278")},"TotalEngagementDuration1518-2278":function(){Enabler.counter("TotalEngagementDuration1518-2278")},"TotalSessionDuration1518-2278":function(){Enabler.counter("TotalSessionDuration1518-2278")},"SpritesheetEngagementDuration2278-3417":function(){Enabler.counter("SpritesheetEngagementDuration2278-3417")},
"TotalEngagementDuration2278-3417":function(){Enabler.counter("TotalEngagementDuration2278-3417")},"TotalSessionDuration2278-3417":function(){Enabler.counter("TotalSessionDuration2278-3417")},"SpritesheetEngagementDuration3417-5125":function(){Enabler.counter("SpritesheetEngagementDuration3417-5125")},"TotalEngagementDuration3417-5125":function(){Enabler.counter("TotalEngagementDuration3417-5125")},"TotalSessionDuration3417-5125":function(){Enabler.counter("TotalSessionDuration3417-5125")},"SpritesheetEngagementDuration5125-7688":function(){Enabler.counter("SpritesheetEngagementDuration5125-7688")},
"TotalEngagementDuration5125-7688":function(){Enabler.counter("TotalEngagementDuration5125-7688")},"TotalSessionDuration5125-7688":function(){Enabler.counter("TotalSessionDuration5125-7688")},"SpritesheetEngagementDuration7688-11533":function(){Enabler.counter("SpritesheetEngagementDuration7688-11533")},"TotalEngagementDuration7688-11533":function(){Enabler.counter("TotalEngagementDuration7688-11533")},"TotalSessionDuration7688-11533":function(){Enabler.counter("TotalSessionDuration7688-11533")},
"SpritesheetEngagementDuration11533-17299":function(){Enabler.counter("SpritesheetEngagementDuration11533-17299")},"TotalEngagementDuration11533-17299":function(){Enabler.counter("TotalEngagementDuration11533-17299")},"TotalSessionDuration11533-17299":function(){Enabler.counter("TotalSessionDuration11533-17299")},"SpritesheetEngagementDuration17299-25949":function(){Enabler.counter("SpritesheetEngagementDuration17299-25949")},"TotalEngagementDuration17299-25949":function(){Enabler.counter("TotalEngagementDuration17299-25949")},
"TotalSessionDuration17299-25949":function(){Enabler.counter("TotalSessionDuration17299-25949")},"SpritesheetEngagementDuration25949-38923":function(){Enabler.counter("SpritesheetEngagementDuration25949-38923")},"TotalEngagementDuration25949-38923":function(){Enabler.counter("TotalEngagementDuration25949-38923")},"TotalSessionDuration25949-38923":function(){Enabler.counter("TotalSessionDuration25949-38923")},"SpritesheetEngagementDuration38923-58385":function(){Enabler.counter("SpritesheetEngagementDuration38923-58385")},
"TotalEngagementDuration38923-58385":function(){Enabler.counter("TotalEngagementDuration38923-58385")},"TotalSessionDuration38923-58385":function(){Enabler.counter("TotalSessionDuration38923-58385")},"SpritesheetEngagementDuration58385-87578":function(){Enabler.counter("SpritesheetEngagementDuration58385-87578")},"TotalEngagementDuration58385-87578":function(){Enabler.counter("TotalEngagementDuration58385-87578")},"TotalSessionDuration58385-87578":function(){Enabler.counter("TotalSessionDuration58385-87578")},
"SpritesheetEngagementDuration87578-131368":function(){Enabler.counter("SpritesheetEngagementDuration87578-131368")},"TotalEngagementDuration87578-131368":function(){Enabler.counter("TotalEngagementDuration87578-131368")},"TotalSessionDuration87578-131368":function(){Enabler.counter("TotalSessionDuration87578-131368")},"SpritesheetEngagementDuration131368-":function(){Enabler.counter("SpritesheetEngagementDuration131368-")},"TotalEngagementDuration131368-":function(){Enabler.counter("TotalEngagementDuration131368-")},
"TotalSessionDuration131368-":function(){Enabler.counter("TotalSessionDuration131368-")}};var n=function(a,b,d){if(d){var e=document.createEvent("CustomEvent");e.initCustomEvent(a,!0,!0,d)}else e=document.createEvent("Event"),e.initEvent(a,!0,!0);b.dispatchEvent(e)},p=function(a,b){var d=function(e){a.removeEventListener("ready",d);b(e)};a.addEventListener("ready",d)};var q=function(){};goog.inherits(q,HTMLElement);q.prototype.createdCallback=function(){this.c=null;this.h="";this.s=this.v.bind(this);this.o=this.i=this.j=this.l=this.m=!1;this.f=null};q.prototype.attachedCallback=function(){window.addEventListener("message",this.s,!1);r(this)};q.prototype.detachedCallback=function(){window.removeEventListener("message",this.s,!1);this.f&&(clearTimeout(this.f),this.f=null)};q.prototype.attributeChangedCallback=function(a){switch(a){case "id-url":case "enable-thumbnail":case "enable-spritesheet":case "enable-quicklook":case "transparent":r(this)}};
var t=function(a){a.c||(a.c=a.ownerDocument.createElement("iframe"),a.c.setAttribute("sandbox","allow-same-origin allow-scripts"),a.c.setAttribute("scrolling","no"),a.c.style.overflow="hidden",a.c.style.border="0",a.c.style.width="100%",a.c.style.height="100%",a.c.addEventListener("load",a.u.bind(a)),a.appendChild(a.c));return a.c},r=function(a){a.f||(a.f=setTimeout(a.gwdLoad.bind(a),0))};c=q.prototype;
c.gwdLoad=function(){this.f&&(clearTimeout(this.f),this.f=null);var a=this.h,b=this.l,d=this.j,e=this.i,u=this.o;this.h=(this.getAttribute("id-url")||"").trim();this.l=this.hasAttribute("enable-thumbnail");this.j=this.hasAttribute("enable-spritesheet");this.i=this.hasAttribute("enable-quicklook");this.o=this.hasAttribute("transparent");this.m=!this.h;if((a!==this.h||b!==this.l||d!==this.j||e!==this.i||u!==this.o)&&this.h){if(a=this.h)b=a.match(f),b&&b[2]||(a=(b=a.match(g))&&b[1]?"https://www.gstatic.com/vr/ads/index.html?assetId="+
b[1]:"https://www.gstatic.com/vr/ads/index.html?assetId="+a),a=encodeURI(a);a+="&thumbnail="+this.l;a+="&spritesheet="+this.j;a+="&quicklook="+this.i;a+="&bg="+!this.o;if("localhost"==window.location.hostname||"file:"==window.location.protocol)a+="&cache=false";t(this).setAttribute("src",a)}};c.gwdIsLoaded=function(){return this.m};c.u=function(){this.m=!0;n("ready",this)};
c.v=function(a){if(window.Enabler&&"https://www.gstatic.com"===a.origin&&a.data)if("string"===typeof a.data){a=a.data.split(":");var b=a[1];switch(a[0]){case "cumulativecounter":if(l[b])l[b]();break;case "noncumulativecounter":if(m[b])m[b]();break;case "starttimer":if(h[b])h[b]();break;case "stoptimer":if(k[b])k[b]();"TimeToClick"==b&&this.click()}}else"OnCameraChanged"===a.data.name?n("camera-changed",this,a.data):"OnHotspotClicked"===a.data.name&&n("hotspot-clicked",this,a.data)};
c.setYaw=function(a,b){this.a({name:"setYaw",yawAngle:a,pauseRestingAnimation:b})};c.setTargetYaw=function(a){this.a({name:"setTargetYaw",yawAngle:a})};c.setTargetPitch=function(a){this.a({name:"setTargetPitch",pitchAngle:a})};c.incrementTargetPitch=function(a){this.a({name:"incrementTargetPitch",pitchAngle:a})};c.setTargetZoom=function(a){this.a({name:"setTargetZoom",scale:a})};c.incrementTargetZoom=function(a){this.a({name:"incrementTargetZoom",scale:a})};
c.setTargetPivot=function(a,b,d){this.a({name:"setTargetPivot",X:a,Y:b,Z:d})};c.setTargetLocalPan=function(a,b,d){this.a({name:"setTargetLocalPan",X:a,Y:b,Z:d})};c.setMaterialColor=function(a,b,d,e){this.a({name:"setMaterialColor",material:a,r:b,g:d,b:e})};c.setMaterialClearCoat=function(a,b,d){this.a({name:"setMaterialClearCoat",material:a,value:b,roughness:d})};c.playAnimation=function(a){this.a({name:"animationPlay",animationName:a})};
c.pauseAnimation=function(a){this.a({name:"animationPause",animationName:a})};c.setAnimationTime=function(a,b){this.a({name:"animationSetTime",animationName:a,time:b})};c.incrementAnimationTime=function(a,b){this.a({name:"animationIncrementTime",animationName:a,time:b})};c.addHotspot=function(a,b,d,e){this.a({name:"addHotspot",hotspotName:a,x:b,y:d,z:e})};c.lookAtHotspot=function(a){this.a({name:"lookAtHotspot",hotspotName:a})};
c.a=function(a){this.m?t(this).contentWindow.postMessage(a,"https://www.gstatic.com"):p(this,this.a.bind(this,a))};document.registerElement("gwd-3d-model",{prototype:q.prototype});}).call(this);
